### ISSUE TITLE
FPS Counter

### ISSUE THREAD

**Issue by LuanTeles** [TheRouletteBoi/RouLetteVshMenu#1]
Can a standalone fps counter be created? that stays on the screen all the time enabled/disabled by simple buttom combo?

**Comment by TheRouletteBoi** [comment]
I will make a new branch for this specifically. Although I will say the text overlay only displays while on XMB mode and can not be displayed over the game/apps

**Comment by LuanTeles** [comment]
No way for in-game? i think you can take a look at in-game vsh menu plugin, it opens a vsh while in-game

**Comment by TheRouletteBoi** [comment]
There is no way to do it in-game with a vsh plugin at least from what I know. The method used in "in-game vsh menu plugin" loads a sperate sprx plugin into the game but the method of drawing is called bitting which requires you to pause the RSX/GPU.

**Comment by TheRouletteBoi** [comment]
Reopening since I figured out how to draw while in-game using vsh text. So it turns out it was just a bug in my code. I've fixed it and made a new branch [standalone-fps-counter](https://github.com/TheRouletteBoi/RouLetteVshMenu/tree/standalone-fps-counter) 

If you can test run and let me know if you find any issues. 
[VshFpsCounter.sprx](https://gofile.io/d/2giocd)
