### ISSUE TITLE
[Feature Request] Automatic Detect YAML changes

### ISSUE THREAD

**Issue by LuanTeles** [TheRouletteBoi/RouLetteVshMenu#20]
I made a nice XMBML menu using webMAN MOD commands to enable/disable the features by editing the yaml file, can the plugin detect that the yaml file has been edited/changed and atomatically loads the new values?

**Comment by TheRouletteBoi** [comment]
it's possible but I would not recommended it since this plugin is supposed to be lightweight, In fact I did implement the feature but blocked in the release versions. 
https://github.com/TheRouletteBoi/RouLetteVshMenu/blob/784d9842c2ed7a8eba17de475e38d8f0d0e4754e/src/Core/Overlay.cpp#L16-L20 
I would suggest either making your command to save and reboot like webman does with their config or build the project source using the fps branch standalone-fps-counter-v2
