### ISSUE TITLE
[Feature Request] PlayTime

### ISSUE THREAD

**Issue by PS3-4K-Pro** [TheRouletteBoi/RouLetteVshMenu#30]
Can a playtime option be added, to show the current playtime session and a total as well?

**Comment by LuanTeles** [comment]
Seems like it only works when  showPlayTime is set to On in both XMB and GAME but the playtime will display the time since the system was booted

I think you can compare de code with webMAN MOD.

Also when this feature is enabled in the XMB enviroment it could say Startup Time and when in game Play Time.
